version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1
  browser-tools: circleci/browser-tools@1.2.3

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk  # Utilisez une image Docker avec Java 8 ou supérieur

    working_directory: ~/app

    steps:
      - checkout

      # Exécutez les tests unitaires avec Maven
      - run:
          name: Run Unit Tests
          command: mvn test

      # Téléchargez les rapports de couverture vers Codecov
      - codecov/upload

      - store_artifacts:
          path: target


workflows:
  version: 2
  upload-to-codecov:
    jobs:
      - checkout
      - codecov/upload
      - build:
          filters:
            branches:
              only: master





