version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk  # Utilisez une image Docker avec Java 8 ou supérieur

    working_directory: ~/app

    steps:
      - checkout

      # Configurez Java
      - run:
          name: Set Java version
          command: |
            sudo update-alternatives --set java /usr/lib/jvm/jdk1.8.0_version/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/jdk1.8.0_version/bin/javac

      # Exécutez les tests unitaires avec Maven
      - run:
          name: Run Unit Tests
          command: mvn test

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
