version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk  # Utilisez une image Docker avec Java 8 ou supérieur

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: Run Unit Tests
          command: mvn test

      - run:
          name: Generate JaCoCo Report
          command: mvn jacoco:report


      - store_artifacts:
          path: target

  codecov-job:
    docker:
      - image: cimg/base:stable
    steps:
      - codecov/upload:
          file: target/my-reports/jacoco.xml

workflows:
  version: 2
  upload-to-codecov:
    jobs:
      - build:
          filters:
            branches:
              only: master

