version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk  # Use a Docker image with Java 8 or higher
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: mvn test
      - store_artifacts:
          path: target
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check
      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report
      - persist_to_workspace:
          root: ~/app
          paths:
            - target

  codecov-job:
    docker:
      - image: cimg/openjdk:18.0.2
    steps:
        - checkout
        - run:
            name: Install dependencies
            command: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
        - run:
            name: Run tests and collect coverage
            command: mvn -B test
        - codecov/upload


workflows:
  version: 2
  codecov-job:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - codecov-job:
          requires:
            - build
