version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk  # Utilisation d'une image Docker avec Java 8 ou supérieur
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Exécuter les tests unitaires
          command: mvn test
      - store_artifacts:
          path: target

  codecov-job:
    docker:
      - image: cimg/openjdk:18.0.2
    steps:
      - checkout
      #- run:
        #    name: Installer les dépendances
      #command: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - run:
          name: Exécuter les tests et collecter la couverture
          command: mvn clean test jacoco:report
      - run:
          name: Téléverser la couverture sur Codecov
          command: bash <(curl -s https://codecov.io/bash)
          uses: codecov/codecov-action@v4-beta
          env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  checkstyle-job:
    docker:
      - image: cimg/openjdk:18.0.2
    steps:
      - checkout
      - run:
          name: Exécuter Checkstyle
          command: mvn checkstyle:checkstyle
      - store_artifacts:
          path: target/checkstyle-result.xml

  javadoc-job:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
        - checkout
        - run:
            name: Generate Javadoc
            command: mvn javadoc:javadoc
        - run:
            name: Deploy Javadoc to GitHub Pages
            command: |
              mkdir -p _site
              cp -R target/site/apidocs/* _site/
            env:
              GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}



workflows:
  version: 2
  codecov-job:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - codecov-job:
          requires:
            - build
      - checkstyle-job:
          requires:
            - build
      - javadoc-job:
          requires:
            - build

