version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk  # Utilisez une image Docker avec Java 8 ou supérieur

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: Run Unit Tests
          command: mvn test

      - store_artifacts:
          path: target

      - checkstyle:
          name : Run Checkstyle
          commands: mvn site


  codecov-job:
    docker:
      - image: circleci/openjdk:8-jdk  # Utilisez une image Docker avec Java 8 ou supérieur

    steps:
      - checkout

      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report

      - run:
          name: Upload Coverage Report
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  codecov-job:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - codecov-job:
          requires:
            - build
