name: Publish Javadoc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Deploy Javadoc to GitHub Pages
        run: |
          mkdir -p _site
          cp -R target/site/apidocs/* _site/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
